### ISSUE TITLE
Kurama is not here yet

### ISSUE THREAD

**Issue by KURAMAAA0** [CheaterTim/DFLore#7]

**Comment by KURAMAAA0** [comment]
In about a month everyone of DF will know me
https://cdn.discordapp.com/emojis/862759661530120222.gif?size=48

**Comment by CheaterTim** [comment]
by the way, you can embed images like this: `![image](https://cdn.discordapp.com/emojis/862759661530120222.gif?size=48)`
![image](https://cdn.discordapp.com/emojis/862759661530120222.gif?size=48)
